# Generated by Django 6.1.1 on 2026-10-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Lector'), ('author', 'Escritor / Autor')], default='reader', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Biografía corta del usuario', max_length=500)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150')),
                ('favorite_genres', models.CharField(blank=True, help_text='Géneros favoritos separados por comas', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
