# Generated by Django 6.1.1 on 2026-10-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría / Género',
                'verbose_name_plural': 'Categorías / Géneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('synopsis', models.TextField(help_text='Sinopsis y descripción de la novela ligera')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='novels/covers/')),
                ('cover_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500', help_text='URL externa de la portada si no sube archivo')),
                ('status', models.CharField(choices=[('ongoing', 'En Emisión'), ('completed', 'Finalizada'), ('hiatus', 'En Pausa'), ('draft', 'Borrador')], default='ongoing', max_length=20)),
                ('demography', models.CharField(choices=[('shonen', 'Shonen'), ('seinen', 'Seinen'), ('shoujo', 'Shoujo'), ('josei', 'Josei'), ('general', 'General')], default='general', max_length=20)),
                ('language', models.CharField(default='Español', max_length=30)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='novels', to='novels.category')),
            ],
            options={
                'verbose_name': 'Novela Ligera',
                'verbose_name_plural': 'Novelas Ligeras',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.FloatField(help_text='Ej: 1, 2, 2.5')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Texto completo del capítulo')),
                ('author_notes', models.TextField(blank=True, help_text='Notas o comentarios del autor')),
                ('is_published', models.BooleanField(default=True)),
                ('words_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['chapter_number'],
                'unique_together': {('novel', 'chapter_number')},
            },
        ),
    ]
