# Generated by Django 6.1.1 on 2026-10-01 22:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('lightnovel', 'Novela Ligera (MAL)'), ('original_novel', 'Novela Original')], max_length=20)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_title', models.CharField(blank=True, max_length=255)),
                ('discussion_type', models.CharField(choices=[('comment', 'Comentario'), ('question', 'Pregunta / Duda')], default='comment', max_length=20)),
                ('content', models.TextField(help_text='Contenido del comentario o pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='catalog.itemdiscussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discusión / Comentario',
                'verbose_name_plural': 'Discusiones y Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_title', models.CharField(max_length=255)),
                ('item_image', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('reading_watching', 'Leyendo / Viendo'), ('plan_to_read_watch', 'Por Leer / Ver'), ('completed', 'Completado'), ('favorite', 'Favorito')], default='favorite', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marcador / Favorito',
                'verbose_name_plural': 'Marcadores y Favoritos',
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('lightnovel', 'Novela Ligera (MAL)'), ('original_novel', 'Novela Original')], max_length=20)),
                ('item_id', models.CharField(db_index=True, help_text='ID de Tenrai MAL o slug de novela', max_length=100)),
                ('item_title', models.CharField(max_length=255)),
                ('item_image', models.URLField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(help_text='Clasificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(help_text='Título de la opinión', max_length=150)),
                ('opinion', models.TextField(help_text='Texto detallado de la opinión o reseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opinión / Reseña',
                'verbose_name_plural': 'Opiniones y Reseñas',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
